name: build

on:
  push:
    branches:
      - 'main'
    pull_requests:
      - 'main'
  repository_dispatch:
    types: [nightly]

env:
  HVCC_VERSION: 89446f737e2b8bc7794fbdd4de2dcce2cb43c874


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v13
        with:
          # Make sure to set a version number!
          version: 3.1.51
          # This is the name of the cache folder.
          # The cache folder will be placed in the build directory,
          #  so make sure it doesn't conflict with anything!
          actions-cache-folder: 'emsdk-cache'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install pinned hvcc
        run: |
          python -m pip install git+https://github.com/Wasted-Audio/hvcc.git@${{ env.HVCC_VERSION }}
        if: ${{ !github.event.client_payload.nightly }}
      - name: Install develop hvcc
        run: |
          python -m pip install git+https://github.com/Wasted-Audio/hvcc.git@${{ github.event.client_payload.branch }}
        if: ${{ github.event.client_payload.nightly }}

      - name: Build plugins
        run: |
            make -j $(nproc)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.0

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
